[build-system]
requires = [
    "setuptools>=61.0.0",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "odpmkd"
version = "0.0.1"

[project.scripts]
odpmkd = "odpmkd.__main__:main"