[build-system]
requires = [
    "setuptools"
]
build-backend = "setuptools.build_meta"

[project]
name = "odpmkd"
dynamic = ["version"]

[tool.setuptools.dynamic]
version = {attr = "odpmkd.VERSION"}

[project.scripts]
odpmkd = "odpmkd.__main__:main"