name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Basic tests
        run: |
          python -m unittest discover -s tests -p 'tests_basic.py'
      - name: Build package
        # We are using setup.py because, AFAIK, is the only way o add a
        # DEV tag to the version of the package (so it is clearly a development
        # version, but we still can have incremental versioning)
        run: |
          python3 setup.py egg_info -bDEV bdist_wheel rotate -m.whl -k2
