name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
            python -m pip install --upgrade wheel
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Basic tests
        run: |
          python -m unittest discover -s tests -p 'tests_basic.py'
      - name: Build package
        # For now, every version is an alpha (i.e., CI produced) version.
        # The base version is an attribute in __init__.py.
        # To get the incremental numbering after the "a", we use YYYYMMDDHHMM
        run: |
          python setup.py egg_info -b "a`date '+%Y%m%d%H%M'`" bdist_wheel
      - name: Retrieve version
        run: |
          echo "VERSION_TAG=$(find dist -name '*.whl' | awk -F'-' '{ print $2 }')" >> $GITHUB_OUTPUT
        id: version
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*.whl"
          commit: "main"
          tag: v${{ steps.version.outputs.VERSION_TAG }}

